# Pre-commit hooks for Precision Guitar Tuner
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # General code quality hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.(md|rst)$
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: mixed-line-ending
        args: ['--fix=lf']

  # C++ formatting with clang-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8
    hooks:
      - id: clang-format
        files: \.(cpp|hpp|c|h|cc|cxx)$
        exclude: ^external/(stb|pffft|rtaudio)/
        args: ['-i', '--style=file']

  # CMake formatting
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        args: ['--config-files', '.cmake-format']
      - id: cmake-lint
        args: ['--config-files', '.cmake-format']

  # C++ static analysis and linting
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      # Static analysis with clang-tidy
      - id: clang-tidy
        args: ['--config-file=.clang-tidy']
        exclude: ^external/

      # Additional static analysis with cppcheck
      - id: cppcheck
        args:
          - '--enable=warning,style,performance,portability'
          - '--inline-suppr'
          - '--suppress=missingIncludeSystem'
        exclude: ^external/

      # Google C++ style checking (adjusted for Allman braces)
      - id: cpplint
        args:
          - '--filter=-whitespace/braces,-whitespace/indent'
          - '--linelength=120'
        exclude: ^external/

      # Code smell detection with oclint
      - id: oclint
        args: ['--']
        exclude: ^external/

      # Include optimization
      - id: include-what-you-use
        args: ['--']
        exclude: ^external/

# Global configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
